### ISSUE TITLE
Anisotropy gets exponentially slower as number of lines increases

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#204] opened 2020-03-04 11:48 UTC
**Describe the bug**
As lines increases, Anisotropy slows down exponentially.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a binary image
2. Run the following macro (note, you will need somehow to disable the warning messages)
```
nDirsMax = 16384;
nLinesMax = 512;
row = 0;
setBatchMode(true);
for (nDirs = 16; nDirs <= nDirsMax; nDirs *= 2){
    for (nLines = 1; nLines <= nLinesMax; nLines *= 2){
		startTime = getTime();
		run("Anisotropy", "inputimage=net.imagej.ImgPlus@73956688 directions="+nDirs+" lines="+nLines+" samplingincrement=1.73 recommendedmin=true printradii=true printeigens=true displaymilvectors=false");
    	endTime = getTime();
    	duration = endTime - startTime;
    	setResult("nDirs", row, nDirs);
    	setResult("nLines", row, nLines);
    	setResult("Duration", row, duration);
    	updateResults();
    	row++;
    }
}
```
Output looks like below: Note the approximately square (²) growth of duration for the larger numbers of lines. Also seems to be ~300 ms of overhead for every run. There is likely to be something multiplied by itself during setup or some unnecessary recursion in an inner loop.
```
n      nDirs  nLines   Duration (ms)
1	16	1	2460
2	16	2	532
3	16	4	326
4	16	8	358
5	16	16	429
6	16	32	447
7	16	64	517
8	16	128	907
9	16	256	2593
10	16	512	8567
11	32	1	310
12	32	2	330
13	32	4	314
14	32	8	329
15	32	16	346
16	32	32	432
17	32	64	566
18	32	128	1323
19	32	256	4277
20	32	512	19143
21	64	1	369
22	64	2	349
23	64	4	334
24	64	8	410
25	64	16	381
26	64	32	529
27	64	64	949
28	64	128	2929
29	64	256	10994
30	64	512	37867
31	128	1	320
32	128	2	323
33	128	4	399
34	128	8	395
35	128	16	410
36	128	32	623
37	128	64	1550
38	128	128	5230
39	128	256	19403
40	128	512	75892
41	256	1	360
42	256	2	330
43	256	4	345
44	256	8	377
45	256	16	483
46	256	32	934
47	256	64	2752
48	256	128	10002
49	256	256	41752
50	256	512	164395
51	512	1	308
52	512	2	351
53	512	4	335
54	512	8	365
55	512	16	610
56	512	32	1307
57	512	64	4476
58	512	128	21686
59	512	256	82923
```

**Expected behavior**
Duration should scale linearly with number of lines because all that should be changing is the number of pixel lookups, and these should be in direct proportion to the number of lines.

**Additional context**
Adding more directions seems to scale linearly or better than linearly.

**Comment by rimadoma** [comment] 2020-03-04 14:09
The plugin is behaving as expected. The parameter _lines per dimension_ may not have the best name, but it is documented both in the code, and on the wikis. For example, if you set it _2_ then the algorithm shoots lines from the two different _x_ and _y_ halves of the plane, i.e. _4_ in total. It squares the work, so _O(n^2)_ is expected.

Early on you told me that you didn't want the lines to be completely random, so that they wouldn't for example all cluster in one corner. How I implemented your idea is that you give the number of lines per dimension or sections _s_. The first line is then randomly positioned within it's _(w/s, h/s)_ section of the plane. The following lines have the same random offset within their sections. This means that the lines are evenly spaced within a square on the plane. If more lines need to be sampled after all the sections have been covered (i.e. MIL length hasn't yet been reached), the cycle begins anew with a new random offset.

Adding more directions should scale _O(n)_ so that makes sense too. If it seemingly runs better than that, it's because the parallellisation kicks in. Early on I did try sampling the individual lines of a direction in parallel, but that wasn't efficient.

**Comment by rimadoma** [comment] 2020-03-04 17:18
Would it be better if the parameter would just be called "lines" and then the algorithm would work:
```
long sections = (long) Math.sqrt(lines);
linegenerator.setSections(sections);
long goalLength = lines * MAGIC_NUMBER;
long sampledLength = 0;
while (sampledLength < goalLength) {
    Line line = lineGenerator.next();
    ... 
} 
```

**Comment by mdoube** [comment] 2020-03-05 01:19
Intuitively, I expect that `lines` relates to the number of traversals of the image by the line probe in a given direction. One way to achieve that is to have a total traversal length that is a multiple of some measure of image size (e.g. diagonal length). Then number of traversals ("lines") would be total traversal length / image size. Or, it could be calculated the other way as you propose above, where `lines` is ~number of traversals and `MAGIC_NUMBER` is the image diagonal `sqrt(w*w + h*h + d*d)`.

I like the idea of a fixed sampling distance in each direction: it means that every pixel has an equal chance of being sampled from every direction: there is the same length of line probe in the image at each direction.

**Comment by rimadoma** [comment] 2020-03-05 13:49
> One way to achieve that is to have a total traversal length that is a multiple of some measure of image size (e.g. diagonal length). 

That is how it works. At the moment "magic number" is the biggest dimension, but I'll make it diagonal when I change the input parameter. This will make the plugin run slightly longer.

**Comment by mdoube** [comment] 2020-03-06 01:57
This is basically working, but if lines is set too low it never finishes, I guess because there is not enough image for the lines to go through to reach `goalLength`. This case should be detected and handled in a user-transparent way (i.e. not with a blocking dialog).

**Comment by mdoube** [comment] 2020-03-06 03:12
![image](https://user-images.githubusercontent.com/87103/76046621-593d9880-5f9b-11ea-8402-000d334a9fd7.png)

**Comment by mdoube** [comment] 2020-03-06 03:16
Above is convergence data on [Uploading binary_noise.tif.zip…](binary noise), using this script (after disabling popup messages by commenting them out in the code):
```
nDirsMax = 16384;
nLinesMax = 65536;
row = 0;
setBatchMode(true);
for (nDirs = 16; nDirs <= nDirsMax; nDirs *= 2){
    for (nLines = 16; nLines <= nLinesMax; nLines *= 2){
		startTime = getTime();
		run("Anisotropy", "inputimage=net.imagej.ImgPlus@73956688 directions="+nDirs+" lines="+nLines+" samplingincrement=1.73 recommendedmin=true printradii=true printeigens=true displaymilvectors=false");
    	endTime = getTime();
    	duration = endTime - startTime;
    	setResult("nDirs", row, nDirs);
    	setResult("nLines", row, nLines);
    	setResult("Duration", row, duration);
    	updateResults();
    	row++;
    	wait(100);
    }
    wait(100);
}
```

Sample output:

```
n      nDirs  nLines   duration (ms)
40	128	16	133
41	128	32	121
42	128	64	140
43	128	128	132
44	128	256	148
45	128	512	188
46	128	1024	237
47	128	2048	348
48	128	4096	574
49	128	8192	1058
50	128	16384	2058
51	128	32768	3844
52	128	65536	7705
53	256	16	143
54	256	32	128
55	256	64	155
56	256	128	152
57	256	256	180
58	256	512	243
59	256	1024	365
60	256	2048	590
61	256	4096	1082
62	256	8192	1992
63	256	16384	3794
64	256	32768	7295
65	256	65536	14795
```

**Comment by rimadoma** [comment] 2020-03-06 14:17
> This is basically working, but if lines is set too low it never finishes, 

Is this a bug? How do you reproduce it? I can't reproduce it, even if lines = 1, directions = 1

**Comment by rimadoma** [comment] 2020-03-06 14:57
> This is basically working, but if lines is set too low it never finishes

Fixed in https://github.com/bonej-org/BoneJ2/pull/208/commits/f5ab938aa424197bec052b724d981ce606785221! Pretty classic floating point bug. I was only able to reproduce it when lines = 1.

**Closed** 2020-03-09 14:58 UTC
Labels: enhancement
